architect:
  - ammaratef45
docker:
  as_root: true
  image: ammaratef45/flutter:v3
  
decrypt:
  repo/attendance/android/api-project.json: "repo/attendance/android/api-project.json.asc"
  repo/attendance/android/key.properties: "repo/attendance/android/key.properties.asc"
  repo/attendance/exportEnvVars.sh: "repo/attendance/exportEnvVars.sh.asc"
  repo/attendance/adminsdk.json: "repo/attendance/adminsdk.json.asc"


merge:
  script: |-
    flutter doctor
    cd attendance
    chmod +x cleanENV.sh && ./cleanENV.sh
    flutter packages get
    . exportEnvVars.sh >/dev/null
    flutter test
    flutter -v build apk
    . /etc/profile.d/rvm.sh
    pdd -f /dev/null -v
    
