version: 2
jobs:
  build:
    docker:
      - image: adamantium/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: cd attendance && flutter packages get && dartanalyzer --options analysis_options.yaml .
      - run: cd attendance && flutter test --coverage
