version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: ammaratef45/flutter:v2
    steps:
      - checkout
      - run: flutter doctor
      - run: cd attendance && flutter packages get && dartanalyzer --options analysis_options.yaml .
      - run: cd attendance && chmod +x cleanENV.sh && ./cleanENV.sh && flutter test --coverage
      - codecov/upload:
          file: 'attendance/coverage/lcov.info'
