version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: adamantium/flutter
    steps:
      - checkout
      - run: apt-get update && apt-get install -y wget && apt-get install -y build-essential && apt-get install -y zlib1g && apt-get install zlib1g-dev
      - run: wget https://www.python.org/ftp/python/3.6.7/Python-3.6.7.tgz && tar xvzf Python-3.6.7.tgz && cd Python-3.6.7 && ./configure && make && make install
      - run: flutter doctor
      - run: cd attendance && flutter packages get && dartanalyzer --options analysis_options.yaml .
      - run: cd attendance && chmod +x cleanENV.sh && ./cleanENV.sh && ls && flutter test --coverage
      - codecov/upload:
          file: 'attendance/coverage/lcov.info'
